blank_issues_enabled: false
contact_links:
  - name: 1. Please read
    url: https://books.ropensci.org/targets/help.html
    about: How to ask for help.
  - name: Discussions
    url: https://github.com/ropensci/targets/discussions
    about: Ask for help or propose an idea.
